#!/bin/bash
case "$5" in
        10.10.20.1)
#                /sbin/route add -net 192.168.111 gw [YOUR VPN GATEWAY]
                /sbin/route add -net 192.168.111 -interface $1
                ;;
#       GATEWAY#2)
#                route command
#                ;;
        *)
esac
exit 0
